modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "superbwarfare"
version = "${mod_version}"
displayName = "Superb Warfare"
authors = "${mod_authors}"
logoFile = "../../resources/logo.png"
description = "${mod_description}"
enumExtensions = "META-INF/enumextensions.json"

[[mixins]]
config = "mixins.superbwarfare.json"

[[dependencies.superbwarfare]]
modId = "neoforge" #mandatory
mandatory = true #mandatory
versionRange = "${neo_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"# Here's another dependency

[[dependencies.superbwarfare]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.superbwarfare]]
modId = "curios"
type = "required"
versionRange = "[5.4.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.superbwarfare]]
modId = "geckolib"
type = "required"
versionRange = "[4.4.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.superbwarfare]]
modId = "optifine"
type = "discouraged"

[[dependencies.superbwarfare]]
modId = "geckoanimfix"
type = "incompatible"

[features.superbwarfare]
openGLVersion = "[3.2,)"